### ISSUE TITLE
Missing documentation on hackage

### ISSUE THREAD

**Issue by hadronized** [leftaroundabout/manifolds#1]
You might want to use my [script](https://github.com/phaazon/stack-haddock-upload) to explicitely upload the documentation if you’re using `stack`. :)

**Comment by leftaroundabout** [comment]
Thanks!
Actually I'm not using Stack (yeah, I now I should be... let's see when I find the time...). But of course it's not ok if the documentation isn't available, so I just used [this tool](http://neilmitchell.blogspot.de/2014/10/fixing-haddock-docs-on-hackage.html) now instead of your script. Documentation [is online](http://hackage.haskell.org/package/manifolds-0.1.5.1) now.

Funny that hackage didn't build it automatically though, after more than a week... any idea why?

**Comment by hadronized** [comment]
That can happen if your package fails to install on the hackage server. You should check the errors on the hackage side.
